### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by sinderwing** [johnnil/Lifelink#11]
Still haven't fully managed buttons. They were *functional* but **fullscreen theme** seems to inherit *constrained*-something that won't allow you to move the buttons around >.>

We will probably have to choose another theme for our app, such as basic, perhaps.

**Comment by angloth** [comment]
Is it possible to create our own theme for better flexibility?

**Comment by sinderwing** [comment]
![android studio](https://cloud.githubusercontent.com/assets/28011537/25543282/1c095d26-2c56-11e7-845f-8d02b2e3f0c7.png)

I don't know why it's so hard

**Comment by angloth** [comment]
I'll make an attempt tomorrow.

**Comment by sinderwing** [comment]
Problem solved. Implemented RelativeLayout instead of FrameLayout.

Switched to empty theme instead of fullscreen theme to avoid future confusion like this when Android Studio has premade something we don't fully understand.
