### ISSUE TITLE
Branching structure proposition

### ISSUE THREAD

**Issue by angloth** [johnnil/Lifelink#12]
I checked out Michel's repository and saw that he had a different branching structure than us and a well defined work flow so I got a bit inspired. Then I read some up online and found this guide: http://nvie.com/posts/a-successful-git-branching-model/

This is basically the work flow and branch structure that I propose that we use:

### Main branches

We should have two **main branches** with **infinite** lifespan: **master** and **develop**.

#### master branch

In **origin/master** the HEAD source code should reflect a production-ready state. The most polished and presentable version of our app that should always be in this branch. We should update **master** in larger sophisticated updates similar to patches. 

#### develop branch

In **origin/develop** the HEAD source code should reflect the latest development progresses that we have been made that we eventually want to patch into **master**. When the changes added to **develop** has become stable enough and we **both** have **reviewed** the changes we add the changes to **master** in the form of a patch tagged with a release number (I guess we have to figure out a how to do proper release numbers as well, might create a new issue for that). 

Development with this branch structure is nicely represented in this image: 

![Borrowed from the article](http://nvie.com/img/main-branches@2x.png)

### Supporting branches

The **supporting branches** are where the actual development and maintenance of the two main branches takes place. There are three types of supporting branches that I think we should use: **feature branches**, **release branches** and **hotfix branches**.

#### Feature branches

The **feature branch** is a branch that is used when you want to add a specific feature or make a specific change to the code in the **develop** branch. 

When you want to add a specific feature or make a specific change you create a *temporary* branch for that specific feature/change and name it something appropriate. You push the changes to this branch and test that they work properly with the code currently in the **develop** branch. When you want the code to be merged you have to do a **pull request** first and then depending on the size of the changes a second opinion review should be requested and performed before the code is merged with **develop** to ensure that nothing will break.  Alternatively the feature branch turns out to be a failed feature and is removed. In either case the branch lifespan is **temporary**.

Here is a good picture that illustrates the lifespan of a **feature branch** and it's relationship with **develop**.

![Borrowed from the article](http://nvie.com/img/fb@2x.png)

There are also some good instructions in the article about how to use certain git commands to make the handling of the **feature branch** easier that I think we should use.

#### Release branches

The **release branch** is a branch type that is used when we want to gather all of the features that we wish to be contained in a specific release. The terminology "release" maybe isn't very relevant in our project and maybe "patch"would be more fitting but I think that it would be a good idea to use as it's probably used in a professional environment. It's a useful branch as it allows for us to continue adding features and making changes to **develop** without affecting the contents a specific scheduled release.

For **release branches** we should have a consistent system with release numbers. In the article they use "release-X" where X is the release number. I think this would be a good way of doing it.

After a **release branch** is branched off from **develop** no more commits from the **develop** branch should be made to the **release branch**. The only changes that should be made on the **release branch** are possible bug fixes after some extended testing. The bug fixes can then also be pushed to the **develop** so that branch also gets updated. When it's time to patch the update you merge the **release branch** with **master** and **develop**.

There are also some good instructions in the article about how to use certain git commands to make the handling of the **release branch** easier that I think we should use.

#### Hotfix branches

**Hotfix branches** are branches made for fixing important bugs that have been detected on **master** that need quick fixing. They ensure that regular development can be pursued on **develop** while a quick fix is made simultaneously. 

 In the article they also use a naming convention for hotfixes that uses the same number as the release number: "hotfix-X" where X is the release number. This is also something I think that we should use.

A **hotfix branch** is branched off from **master**. Changes are then made to the **hotfix branch** that are then tested and reviewed before merging the **hotfix branch** with **master** and **develop**.

Here is another good illustration from the article. It illustrates the lifespan of a **hotfix branch**:

![Borrowed from the article](http://nvie.com/img/hotfix-branches@2x.png)

In the same case as the other supporting branches, there exists good instructions for specific git commands in the article for **hotfix branches**.

### Summary

Here is a good illustration that shows how the different branches work and relate to each other as well as showing their lifespans:

![Borrowed from article](http://nvie.com/img/git-model@2x.png)
_____________________________________________________________________________________________________

What do you think @johnnil ?

**Comment by sinderwing** [comment]
Sounds good.
