### ISSUE TITLE
Propositioned design of different views

### ISSUE THREAD

**Issue by angloth** [johnnil/Lifelink#17]
Here are some primitive designs that I created for the different views. They aren't very polished or anything but could be good to have as some sort of guideline.

![mainpageprimitiveprototype](https://cloud.githubusercontent.com/assets/23058427/25633916/0d304140-2f79-11e7-86c6-06f6762e654c.png)

![creatinglobbyprimitiveprototype](https://cloud.githubusercontent.com/assets/23058427/25633931/1fba9b94-2f79-11e7-9ac1-5234084d59d1.png)

![joininglobbyprimitivedesign](https://cloud.githubusercontent.com/assets/23058427/25634719/eaab918a-2f7b-11e7-9c1d-923736cd65a7.png)

Your design basically with chess clock and some changes. Hold to + or - to increase increment/decrement of health.

<img width="313" alt="inlobbyprimitivedesign" src="https://cloud.githubusercontent.com/assets/23058427/25634843/59e3697e-2f7c-11e7-8ccd-c0747ac4c95f.png">

Was thinking about adding these to the README, what do you think @johnnil ?

**Comment by sinderwing** [comment]
Main page: I like my current implementation better. The lowest buttons are called Change Name and Change Color instead.

Create lobby: brilliant, although I want the slider to go 20, 30, 40 instead.

Total time should indicate that we mean seconds, somehow. It's nice that you can experiment with it :)

In lobby: this is what I currently refer to as Ingame since it should then lose it's lobby characteristics and become a locked game. Perhaps the in lobby could be a list updating when new players join or leave with a START button at the bottom?

**Comment by sinderwing** [comment]
Wouldn't it be awesome if your color was the background color on the whole app? We could probably do that.

**Comment by angloth** [comment]
Main page: Could you upload a picture of the intended design?

Create lobby: Added some marks and says min after. We don't need to polish this so much we just need something that we can work with.

![creatinglobbyprimitiveprototype](https://cloud.githubusercontent.com/assets/23058427/25636430/a1496624-2f81-11e7-8f58-cca9b7c9eb1d.png)

In lobby (in game): Yes maybe, I'll try making something like that tomorrow. However this view is supposed to be in game then I guess.

Background color: Yes maybe, although I would prefer if it was like a slightly lighter version of the chosen color so it looks a bit faded and more like a background. Again though these are just primitive designs so we don't really need to think about color that much.

**Comment by angloth** [comment]
Updated text of "in lobby" to "in game":

![ingameprimitivedesign](https://cloud.githubusercontent.com/assets/23058427/25636668/6c6a314e-2f82-11e7-9a9c-92e190e2729d.png)

**Comment by sinderwing** [comment]
![lifecounter single](https://cloud.githubusercontent.com/assets/28011537/25654294/d1f40526-2ff0-11e7-9646-92e24116a44b.png)
![mainactivity](https://cloud.githubusercontent.com/assets/28011537/25654295/d1f79af6-2ff0-11e7-82b4-7347572e342f.png)

**Comment by angloth** [comment]
What does the "TO INGAME" button do?

**Comment by sinderwing** [comment]
It's a temporary backdoor so I can get to that screen while testing :) It takes me straight to Ingame with the life counter.

**Comment by sinderwing** [comment]
I feel like the basic design is finished now. Closing to register it as a milestone.

**Comment by angloth** [comment]
Woop woop
