### ISSUE TITLE
Main page: The player can change his/her name

### ISSUE THREAD

**Issue by angloth** [johnnil/Lifelink#20]
The player can change his name in the main page by clicking on a button and then typing in his name as input.

**Comment by sinderwing** [comment]
I'm doing this with something called SharedPreferences which allows the info to be stored inbetween app instances, i.e. the data is retained every time you use the app.

**Comment by angloth** [comment]
Nice, do we possibly want to store game settings preferences as well with SharedPreferences?

**Comment by sinderwing** [comment]
That'd be great. I can probably fix that when you're done with the create-a-lobby screen.

**Comment by angloth** [comment]
👍
