### ISSUE TITLE
Main page: The player can change his/her color.

### ISSUE THREAD

**Issue by angloth** [johnnil/Lifelink#21]
The player can change his color in the main page by clicking on a button and then selecting from a selection of colors.

Which colors that should be available also has to be decided.

**Comment by sinderwing** [comment]
You can now change it by entering a html code.

**Comment by sinderwing** [comment]
Possible improvement:
A list of strings like (Green, Red ...) mapped to html codes. Choose a color from there instead.

Less choice compared to straight up html codes, but easier. Still not as good as color chooser.

**Comment by angloth** [comment]
I think that the player should be given the a selection off maybe 16 colors. You don't want to overwhelm the user with too many choices while still allowing for a sense of personalizing the profile.

**Comment by sinderwing** [comment]
Time constraints
