### ISSUE TITLE
Creating lobby: The host is able to set the lifecount for the game.

### ISSUE THREAD

**Issue by angloth** [johnnil/Lifelink#24]
The host is able to set the life count for the game. Preferably via a slider of some sorts. The current life count selected by the slider is displayed by a number below the slider.

What different starting lives should the host be able to choose between @johnnil ? Do we want a full spectrum between some limits or do we just want some common starting lives (such as 20-30-40 for example)?

**Comment by sinderwing** [comment]
Fixed in #54
