### ISSUE TITLE
Creating lobby: The host is able to set the time settings for the game.

### ISSUE THREAD

**Issue by angloth** [johnnil/Lifelink#25]
The host is able to set the time settings for the game. 

First via a slider that slides between three modes: No time, total time and time per player.

For no time no further time settings are needed.

For total time the host sets the total time for the game via a slider. The total time currently selected in the slider is presented via a number below the slider. What total starting times are common @johnnil ?

For time per player the host sets the time per player via a slider. The time per player currently selected in the slider is presented via a number below the slider. What time per players are common @johnnil ?

**Comment by sinderwing** [comment]
Fixed in #54
