### ISSUE TITLE
Make custom launch icon

### ISSUE THREAD

**Issue by sinderwing** [johnnil/Lifelink#37]
Visible on app store, homepage etc.

**Comment by sinderwing** [comment]
![web_hi_res_512](https://cloud.githubusercontent.com/assets/28011537/25750957/bce21e88-31b3-11e7-8c14-d0092e2ba159.png)

**Comment by angloth** [comment]
DAaaaaaaaamn that's sick 🥇

**Comment by sinderwing** [comment]
Aaand properly added to project.
