### ISSUE TITLE
Review: 1. Clear Project Description & Documentation

### ISSUE THREAD

**Issue by AxlLind** [johnnil/Lifelink#42]
Your project description is incredibly clear. You have prototyp-pictures demonstrating how the app will work, explanation for why the app is needed, and very thought out design prototypes.

You talk a lot about your branching structure in the readme but I can't see that you actually use this work flow. You say you should have a development branch used for dev which should reflect the most current changed but from what I can see that branch is 16 commits behind master.

Your code could be commented more explaining what different methods do and what different activities are.

**Comment by sinderwing** [comment]
The branching structure turned out to be overkill.

Will comment more in the code from here on out.
