### ISSUE TITLE
Reivew: 3. Use of Milestones and Features in Issue Tracker

### ISSUE THREAD

**Issue by AxlLind** [johnnil/Lifelink#44]
You use the issue tracker very well I feel. You have issues for larger features you want to implement. It would be nice to maybe comment on these issues if you've made some progress on this in a commit.

You should really use labels on issues so you can easily see what is a suggested feature, what is a bug, what is just an enhancement to something already existing etc.

The use of milestones is done well. You have set up larger features you want implemented etc.

**Comment by sinderwing** [comment]
Will use labels from here on out.
