### ISSUE TITLE
Review: 5. Use of Branching and Pull Requests

### ISSUE THREAD

**Issue by AxlLind** [johnnil/Lifelink#46]
You have a very detailed branching workflow in your readme but I can't see that you follow that.

The branching workflow that you do follow seems good. Looking at the network graph you don't commit directly to master, instead you branch out, do work on that branch and then merge to master which is a good workflow.

You also review each other's pull requests instead of merging them yourself which is good!

**Comment by sinderwing** [comment]
Referenced in #47
