### ISSUE TITLE
Peer Review 1: Clear Project Description & Documentation

### ISSUE THREAD

**Issue by Jontpan** [johnnil/Lifelink#47]
The project description is clear and concise, with low-fi prototypes to back it up. However, you go into great lengths describing your branching structure while seemingly not following it. Which probably means the branching structure, while probably great for big projects, was too much for such a small project that this is. 

The documentation is lacking, but you use clear and descriptive method and variable names.

**Comment by sinderwing** [comment]
Yes, it was overkill, especially since we don't have master as a "finished product on Google Play" yet.

What do you mean when you say the documentation is lacking? All sorts of documentation?

**Comment by angloth** [comment]
@johnnil I think he means code documentation because our other documentation is very complete.
