### ISSUE TITLE
Peer Review 2: Good Commit Log messages

### ISSUE THREAD

**Issue by Jontpan** [johnnil/Lifelink#50]
The commit log messages are good, short and clear. The only thing I could remark upon is that @johnnil doesn't use the imperative mood ("Start working on player profile" instead of "Starting work on player profile") but that's a minor detail. 

Sorry if these reviews are coming slowly, I'm not feeling too well and it's hard to think. :)

**Comment by sinderwing** [comment]
I was even keeping this in mind... I'll keep it twice as much in mind from here on out.

Get well soon!
