### ISSUE TITLE
Peer Review 4: Use of issues to resolve bugs

### ISSUE THREAD

**Issue by Jontpan** [johnnil/Lifelink#52]
There seems to only have been one Issue that have had the bug tag, don't you ever write bad code? Or else it is not clear when you are fixing bugs. Was #19 a bug? It has the weird text of "A button that leads to the page "Joining lobby" is functional". Was this functional or was it not?

**Comment by sinderwing** [comment]
It was an issue to be completed. We had a bunch of those in order to track our progress in milestone and to visualize what need to be implemented
