### ISSUE TITLE
Joining lobby view

### ISSUE THREAD

**Issue by angloth** [johnnil/Lifelink#8]
How does it work when a player wants to join a lobby? Do we want to the view to list all available lobbies on the LAN in a nice list that can be scrolled down?

**Comment by sinderwing** [comment]
That sounds awesome. It'd be nice if it was able to refresh by dragging the list downwards like a lot of apps do nowadays.

**Comment by angloth** [comment]
Alright!

I agree that dragging down to refresh is a good idea!

**Comment by angloth** [comment]
Here is a basic prototype of the design of the lobby browsing view:

![joininglobbyprimitivedesign](https://cloud.githubusercontent.com/assets/23058427/25526428/be42bf3a-2c13-11e7-9dd2-4ba3f8557e69.png)

What do you think?

**Comment by sinderwing** [comment]
Yes! Very clean and intuitive design. Regardless of the open-close feature, this should be our design!

**Comment by angloth** [comment]
Alright. What information do we want to be displayed for each lobby? 

I feel like given are host name and number of players, but maybe game mode is unnecessary information?

**Comment by sinderwing** [comment]
Yeah, host and players should be enough. If we allow an extra text string it'd be more like a matchmaking app and that's not our focus.

**Comment by angloth** [comment]
Yes agreed.
